export const LINE_LABELLING_SET_DOWNLOAD_IMAGE_SIZE =
  'LINE_LABELLING_SET_DOWNLOAD_IMAGE_SIZE';
export const LINE_LABELLING_SET_PREVIEW_IMAGE_SIZE =
  'LINE_LABELLING_SET_PREVIEW_IMAGE_SIZE';
export const SIDER_SET_OPEN_KEYS = 'SIDER_SET_OPEN_KEYS';
export const SIDER_TOGGLE_COLLAPSED = 'SIDER_TOGGLE_COLLAPSED';
export const USER_WEBCAM_SET_FACES_LAYOUT = 'USER_WEBCAM_SET_FACES_LAYOUT';
export const USER_WEBCAM_TOGGLE_AUTO_DETECT = 'USER_WEBCAM_TOGGLE_AUTO_DETECT';
export const USER_WEBCAM_TOGGLE_WEBCAM_VISIBLE =
  'USER_WEBCAM_TOGGLE_WEBCAM_VISIBLE';
