export const TOGGLE_COLLAPSED = 'TOGGLE_COLLAPSED';
export const SET_OPEN_KEYS = 'SET_OPEN_KEYS';

export const TOGGLE_AUTO_DETECT = 'TOGGLE_AUTO_DETECT';
export const TOGGLE_WEBCAM_VISIBLE = 'TOGGLE_WEBCAM_VISIBLE';
export const SET_FACES_LAYOUT = 'SET_FACES_LAYOUT';
